[[actions]]
name = "play"
platform = "windows"
path = "Raingen/Raingen.exe"
args = ["--launched-through-itch"]

[[actions]]
name = "play"
platform = "linux"
path = "Raingen/Raingen"
args = ["--launched-through-itch"]
